# Generated by Django 4.0.2 on 2022-04-27 06:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('api', '0001_initial'), ('api', '0002_income_userid'), ('api', '0003_alter_income_userid'), ('api', '0004_remove_income_userid'), ('api', '0005_income_userid'), ('api', '0006_alter_income_date'), ('api', '0007_user_isloggedin'), ('api', '0008_goal_bill'), ('api', '0009_remove_user_isloggedin')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('incomeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('income', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('isRecurring', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('goalId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('isRecurring', models.BooleanField(default=False)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField(auto_now_add=True)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('billId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('isRecurring', models.BooleanField(default=False)),
                ('dueDate', models.DateTimeField(auto_now_add=True)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
