# Generated by Django 4.0.2 on 2022-05-01 03:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('createdOn', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('incomeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('income', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('isRecurring', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('goalId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal', models.TextField()),
                ('amountNeeded', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monthlyAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('isRecurring', models.BooleanField(default=False)),
                ('startDate', models.DateField(default=datetime.date.today)),
                ('endDate', models.DateField(default=datetime.date.today)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('billId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('isRecurring', models.BooleanField(default=False)),
                ('dueDate', models.DateField(default=datetime.date.today)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
