# Generated by Django 4.0.2 on 2022-05-01 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='isRecurring',
        ),
    ]
