# Generated by Django 4.0.2 on 2022-03-31 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_income_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='userId',
        ),
    ]
