# Generated by Django 4.0.2 on 2022-05-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_goal_isrecurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='amountCommitted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
