# Generated by Django 4.0.2 on 2022-04-07 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_income_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
