# Generated by Django 4.0.2 on 2022-05-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_goal_amountcommitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='amountCommitted',
        ),
        migrations.AddField(
            model_name='goal',
            name='completion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
