# Generated by Django 4.0.2 on 2022-04-26 22:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_isloggedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('goalId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('isRecurring', models.BooleanField(default=False)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField(auto_now_add=True)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('billId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('isRecurring', models.BooleanField(default=False)),
                ('dueDate', models.DateTimeField(auto_now_add=True)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
