# Generated by Django 4.0.2 on 2022-04-15 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_isloggedin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isLoggedIn',
        ),
    ]
