# Generated by Django 4.0.2 on 2022-04-26 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_goal_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isLoggedIn',
        ),
    ]
