# Generated by Django 4.0.2 on 2022-04-28 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_income_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='dueDate',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='goal',
            name='endDate',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdOn',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
