# Generated by Django 4.0.2 on 2022-04-28 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_bill_duedate_alter_goal_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='dueDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='goal',
            name='endDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='goal',
            name='startDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdOn',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
